/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_UsbGadgetHid */

#ifndef _Included_com_example_myapplication_UsbGadgetHid
#define _Included_com_example_myapplication_UsbGadgetHid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_UsbGadgetHid
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_myapplication_UsbGadgetHid_open
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myapplication_UsbGadgetHid
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_UsbGadgetHid_close
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myapplication_UsbGadgetHid
 * Method:    hidSend
 * Signature: (B[BB)I
 */
JNIEXPORT jint JNICALL Java_com_example_myapplication_UsbGadgetHid_hidSend
  (JNIEnv *, jobject, jbyte, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
